### ISSUE TITLE
always restarting

### ISSUE THREAD

**Issue by kapiorr** [ksurl/docker-autodelete-discord#1]
Hey,
I'll try to add Your image. Used this command:

```
docker run -d -p 2202:2202/tcp \
 --name Autodelete \ 
 -v /opt/AutoDelete/config.yml:/autodelete/config.yml \ 
 -v /opt/AutoDelete/data/:/autodelete/data/ \ 
 --restart=always \ 
 ksurl/autodelete-discord
``` 
but it always restarting.

In /opt/AutoDelete/ are directories : data and config.yml
Shouldn't the config.yml be a file?

How I can fix this?

**Comment by ksurl** [comment]
Yes config.yml is a file. Did you create it beforehand with the correct settings? There should be instructions from the original github repo on riking/AutoDelete. Or maybe it's in the discord. Mine is just a separate docker image built on the source code. If the latest one doesn't work, you can try the 1.0 tag also. I recently updated the image with a different build file for 1.1

**Comment by kapiorr** [comment]
Yes. I was try to create file befroe pulling image - it always restarting.
If i delete directory config.yml and add file config.yml not start because not found directory.
Now I compiled it from source and run outside docker.

**Comment by ksurl** [comment]
I just checked and my compose file is different for the path to map. you can try it again and point to:

- /opt/AutoDelete/config.yml:/app/config.yml
- /opt/AutoDelete/data:/app/data

**Comment by kapiorr** [comment]
Now is OK. I don't know where I got these entries.
My bad.
Thx for help
